### ISSUE TITLE
How to compile?

### ISSUE THREAD

**Issue by ajthemacboy** [andrewkm/SkylandsPlus#7]
Hi, just wondering how I compile this?

Update: ran mvn install and got this:

[ERROR] Failed to execute goal on project skylandsplus: Could not resolve dependencies for project uk.co.jacekk.bukkit:skylandsplus:jar:0.16-SNAPSHOT: Could not find artifact org.bukkit:craftbukkit:jar:1.8.7-R0.1-SNAPSHOT in sk89q-repo (http://maven.sk89q.com/repo/) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by JamieSinn** [comment]
You need the CB Jar as a local maven reference. 
use mvn install-file for this.
For a build, see the CI.
http://ci.ecocitycraft.com/view/EcoCityCraft/job/SkyLandsPlus/
