### ISSUE TITLE
Diamond cannot generate

### ISSUE THREAD

**Issue by mrsheepsheep** [andrewkm/SkylandsPlus#8]
Diamond ore cannot generate in the world since minimum island height is above 16 (exactly 16 ?), and it only generates under layer 16 !

**Comment by mrsheepsheep** [comment]
I found a custom ore generator working with SkylandsPlus: http://dev.bukkit.org/bukkit-plugins/oreplus/

**Comment by JamieSinn** [comment]
I know for a fact that I've seen diamonds on the world.
Also, this is more of a maintenance/updated version, not really for extending features.
