### ISSUE TITLE
Chunk Generator isnt working

### ISSUE THREAD

**Issue by Bodyash** [andrewkm/SkylandsPlus#9]
:cactus:

**Comment by JamieSinn** [comment]
errors? info?

**Comment by Bodyash** [comment]
![vcwwxdw 1](https://cloud.githubusercontent.com/assets/2454569/14020827/7ad032a4-f1e1-11e5-845d-f1aa0f39c579.png)

**Comment by JamieSinn** [comment]
1.9 update problem. And that's not the full post.

**Comment by andrewkm** [comment]
Sorry we will no longer be updating/fixing SkyLandsPlus as it is being removed from our server.
